[package]
name = "nightcycle/texture"
description = "Creates a texture object, allowing you to easily apply consistent textures across parts."
version = "0.1.3"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
isotope = "nightcycle/isotope@1.1.15"
coldfusion = "nightcycle/cold-fusion@1.0.19"
signal = "quenty/signal@^2.0.0-canary"
maid = "quenty/maid@^2.0.1-canary"
