[package]
name = "nightcycle/texture"
description = "Creates a texture object, allowing you to easily apply consistent textures across parts."
version = "0.1.4"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
isotope = "nightcycle/isotope@1.1.19"

